---
- hosts: 127.0.0.1
  become: yes
  become_user: ansadmin
  become_method: su  
  var_files:
    - all.yml
  tasks:
  - name: Install tomcat
    yum:
      name: tomcat
      state: latest
  - name: Install additional packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
  - name: copy tomcat-users.xml
    copy:
       src: tomcat-users.xml
       dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: copy application
    copy:
       src: /var/lib/jenkins/workspace/MavenTest/webapp/target/webapp.war
       dest: /var/lib/tomcat/webapps/
  - name: Start tomcat
    service:
       name: tomcat
       state: started
  - name: Enable tomcat
    service:
       name: tomcat
       enabled: yes
